services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuxt.rule=Host(`nuxt.${TOP_LEVEL_DOMAIN}`)"
      - "traefik.http.routers.nuxt.entrypoints=web"
      - "traefik.http.services.nuxt.loadbalancer.server.port=3000"
      - "traefik.http.routers.nuxt.middlewares=authentik@docker"
    env_file:
      - .env

networks:
  traefik:
    external: true
